name: Publish Docs

on:
  push:
    branches: [ 'main' ]
    paths: [ 'docs/**' ]

permissions:
  contents: write

jobs:
  publish-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Wait 2 min to make sure pypi package was updated
        run: sleep 120

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt
